name: Update GitVersion version

permissions:
  contents: read

on:
  repository_dispatch:
    types: [ gitversion-release-published ]

defaults:
  run:
    shell: pwsh

jobs:
  update-gitversion-version:
    if: ${{ github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Auth and Checkout
        id: auth_and_checkout
        uses: gittools/cicd/auth-checkout@main
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          fetch-depth: 0

      - run: |
          $newTag = "${{ github.event.client_payload.tag }}"
          echo "Updating GitVersion version to $newTag"
        name: Update GitVersion version

      - uses: gittools/cicd/git-commit-push@main
        with:
          message: "update GitVersion version to ${{ github.event.client_payload.newTag }}"
        name: Commit and push updated GitVersion version
